[package]
name = "rust-nes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
bitflags = "1.3.2"
image = "0.24.1"
once_cell = "1.10.0"

[features]
